name: PocketCore
author: PocketCore
authors:
- 'Primus'
- 'HotFireyDeath'
website: ~ # I will buy domain and hosting as first build will be available
api:
- 2.0.0
version: 0.0.0
main: pocketcore/PocketCore
